# every value can be changed from command line by preceding the option with --
# see https://docs.spring.io/spring-boot/docs/current/reference/html/spring-boot-features.html#boot-features-external-config-command-line-args
# example:
#   target/fake_oidc_server.jar --server.port=8100 -server.ssl.key-store=mykeystore.p12  --oidc.users.makub.password=bflmpsvz

server:
  port: 8090

oidc:
  tokenExpirationSeconds: 36000
  users:
    perun:
      password: "test"
      sub: "perun1"
      given_name: "Master"
      family_name: "Perun"
      email: "perun@cesnet.cz"
    makub:
      password: "test"
      sub: "makub1"
      given_name: "Martin"
      family_name: "Kuba"
      email: "makub@ics.muni.cz"
  clients:
    default:
      id: "submission-server"
      secret: "testKey"
      
      

spring.profiles.active: ssl

---
 
spring.config.activate.on-profile : ssl

server:
  ssl:
    key-store-type: pkcs12
    # create your own keystore with:
    #  openssl pkcs12 -export -name "mycert" -inkey key.pem -in cert.pem -certfile chain.pem -out mykeystore.p12
    key-store: classpath:keystore.p12
    key-store-password: password